# Generated by Django 5.1.1 on 2024-11-14 19:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Weapon',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('old', 'Old'), ('new', 'New'), ('broken', 'Broken'), ('repaired', 'Repaired')], max_length=100)),
                ('age', models.IntegerField()),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='weaponry.place')),
            ],
        ),
    ]
