# Generated by Django 5.1.1 on 2024-11-17 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weaponry', '0003_place_earnings_place_utility_weapon_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='utility',
            field=models.CharField(choices=[('repair', 'Repair'), ('sell', 'Sell'), ('No utility', 'No utility'), ('earn new weapons', 'Earn new weapons')], default='No utility', max_length=100),
        ),
    ]
